# Simple iOS Simulator Build - GitHub Actions
# File: .github/workflows/ios-simple-build.yml
# Version: LFS Fix

name: Simple iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # [CRITICAL FIX] Add lfs: true to ensure project files are fully downloaded
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true # This is the fix for the project parsing error
    
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
        xcodebuild -version
    
    - name: Install CocoaPods (if needed)
      run: |
        if [ -f "Podfile" ]; then
          echo "Podfile found. Installing dependencies."
          pod install
        else
          echo "No Podfile found. Skipping pod install."
        fi
    
    # This script is now correct, the problem was with the file content
    - name: List Project Info and Set Paths
      id: project_info
      run: |
        echo "=== Searching for project/workspace (excluding .xcodeproj contents) ==="
        ls -laR

        WORKSPACE_PATH=$(find . -name "*.xcodeproj" -prune -o -name "*.xcworkspace" -print | head -n 1)
        PROJECT_PATH=$(find . -maxdepth 3 -name "*.xcodeproj" | head -n 1)

        if [ -n "$WORKSPACE_PATH" ]; then
          echo "✅ Found valid top-level workspace at: $WORKSPACE_PATH"
          echo "WORKSPACE_FILE=${WORKSPACE_PATH}" >> $GITHUB_ENV
          echo "USE_WORKSPACE=true" >> $GITHUB_ENV
          SCHEME_NAME=$(basename "$WORKSPACE_PATH" .xcworkspace)
          echo "PROJECT_NAME=${SCHEME_NAME}" >> $GITHUB_ENV
        elif [ -n "$PROJECT_PATH" ]; then
          echo "✅ No top-level workspace found. Using project at: $PROJECT_PATH"
          echo "PROJECT_FILE=${PROJECT_PATH}" >> $GITHUB_ENV
          echo "USE_WORKSPACE=false" >> $GITHUB_ENV
          SCHEME_NAME=$(basename "$PROJECT_PATH" .xcodeproj)
          echo "PROJECT_NAME=${SCHEME_NAME}" >> $GITHUB_ENV
        else
          echo "❌ Error: Could not find a valid .xcworkspace or .xcodeproj file."
          exit 1
        fi
        
        echo "--- Determined Variables ---"
        echo "PROJECT_NAME: ${SCHEME_NAME}"

    - name: Show Schemes
      run: |
        if [ "$USE_WORKSPACE" == "true" ]; then
          xcodebuild -workspace "$WORKSPACE_FILE" -list
        else
          xcodebuild -project "$PROJECT_FILE" -list
        fi
    
    - name: Build for Simulator
      run: |
        if [ "$USE_WORKSPACE" == "true" ]; then
          BUILD_ARGS="-workspace \"$WORKSPACE_FILE\""
        else
          BUILD_ARGS="-project \"$PROJECT_FILE\""
        fi
        
        xcodebuild build \
          $BUILD_ARGS \
          -scheme "$PROJECT_NAME" \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -sdk iphonesimulator \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Create Archive
      run: |
        if [ "$USE_WORKSPACE" == "true" ]; then
          BUILD_ARGS="-workspace \"$WORKSPACE_FILE\""
        else
          BUILD_ARGS="-project \"$PROJECT_FILE\""
        fi
        
        xcodebuild archive \
          $BUILD_ARGS \
          -scheme "$PROJECT_NAME" \
          -archivePath "build/$PROJECT_NAME.xcarchive" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: build/
        retention-days: 7
