name: Build iOS Simulator App (Dynamic)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-for-simulator:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Select latest stable Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: Get Project and Scheme Info
      id: project_info
      run: |
        # Find the .xcodeproj file automatically
        PROJECT_FILE=$(find . -name "*.xcodeproj" -maxdepth 1)
        if [ -z "$PROJECT_FILE" ]; then
          echo "Error: No .xcodeproj file found in the root directory."
          exit 1
        fi
        PROJECT_NAME=$(basename "$PROJECT_FILE")
        echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_OUTPUT

        # Dynamically find the first non-test scheme.
        # For more complex projects, consider hardcoding this.
        SCHEME=$(xcodebuild -list -project "$PROJECT_FILE" | awk '/Schemes:/,/Build Configurations:/' | grep -v -E '(Schemes:|Pods|Tests|Build Configurations:)' | head -n 1 | xargs)
        if [ -z "$SCHEME" ]; then
          echo "Error: Could not automatically determine a buildable scheme."
          exit 1
        fi
        echo "SCHEME_NAME=${SCHEME}" >> $GITHUB_OUTPUT
        echo "Found Project: ${PROJECT_NAME}"
        echo "Found Scheme: ${SCHEME}"

    - name: Build for iOS Simulator
      run: |
        # The runner architecture (uname -m) is arm64 on macos-14, which is correct for modern simulators
        xcodebuild clean build \
          -project "${{ steps.project_info.outputs.PROJECT_NAME }}" \
          -scheme "${{ steps.project_info.outputs.SCHEME_NAME }}" \
          -destination 'platform=iOS Simulator,OS=latest' \
          -derivedDataPath "build/DerivedData" \
          -arch "$(uname -m)" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Upload Simulator Build (.app)
      uses: actions/upload-artifact@v4
      with:
        name: simulator-build-app
        # The path to the .app file built for the simulator
        path: build/DerivedData/Build/Products/Debug-iphonesimulator/${{ steps.project_info.outputs.SCHEME_NAME }}.app
        retention-days: 5
