# .github/workflows/build-ios.yml

name: Build iOS Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # Use the macos-14 runner, which supports Xcode 16.
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true # Important if your project uses Git LFS for large assets

    # This is the key fix: Use a dedicated action to select the correct Xcode version.
    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        # Specify the Xcode version your project requires.
        # You can use '16.0', '16.1', '16.2', or 'latest-beta' when available.
        # Let's use '16.0' as it's the most common beta version on runners right now.
        xcode-version: '16.2'

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: List Available Schemes
      # This step is useful for debugging to ensure your scheme is visible.
      run: xcodebuild -list -project MusicPlayerApp.xcodeproj

    - name: Build for iOS Simulator
      run: |
        # If your scheme has a different name, change it here.
        # Often, the scheme name matches the project name.
        SCHEME_NAME="MusicPlayerApp"

        echo "🔨 Building scheme '$SCHEME_NAME' for simulator..."
        xcodebuild clean build \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Create Build Archive
      run: |
        SCHEME_NAME="MusicPlayerApp"
        ARCHIVE_PATH="build/$SCHEME_NAME.xcarchive"

        echo "📦 Archiving scheme '$SCHEME_NAME'..."
        xcodebuild archive \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -archivePath "$ARCHIVE_PATH" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          SKIP_INSTALL=NO # Ensures a proper archive structure

    - name: Upload Build Artifact
      # This step will run even if a previous step fails, which is useful for debugging.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-archive
        path: build/
        retention-days: 5
