# .github/workflows/build-ios.yml

name: Build iOS Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Verify Xcode Version and Mac Architecture
      run: |
        xcodebuild -version
        echo "Runner architecture: $(uname -m)"

    - name: List Available Schemes
      run: xcodebuild -list -project MusicPlayerApp.xcodeproj

    # --- THIS STEP IS UPDATED ---
    - name: Build Universal App for Simulators
      run: |
        SCHEME_NAME="MusicPlayerApp"
        DERIVED_DATA_PATH="build/DerivedData"

        echo "🔨 Building Universal scheme '$SCHEME_NAME' for all simulators..."
        xcodebuild clean build \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -destination 'generic/platform=iOS Simulator' \
          -derivedDataPath "$DERIVED_DATA_PATH" \
          -arch x86_64 -arch arm64 \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=NO

    - name: Create Build Archive (for App Store)
      run: |
        SCHEME_NAME="MusicPlayerApp"
        ARCHIVE_PATH="build/$SCHEME_NAME.xcarchive"

        echo "📦 Archiving scheme '$SCHEME_NAME'..."
        xcodebuild archive \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -archivePath "$ARCHIVE_PATH" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          SKIP_INSTALL=NO

    - name: Upload Universal Simulator Build (.app file)
      uses: actions/upload-artifact@v4
      with:
        name: universal-simulator-build-app
        path: build/DerivedData/Build/Products/Debug-iphonesimulator/MusicPlayerApp.app
        retention-days: 5

    - name: Upload Archive Build (.xcarchive)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: archive-build
        path: build/MusicPlayerApp.xcarchive
        retention-days: 5
