name: Build iOS Simulator App (Final & Verified)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-for-simulator:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Select latest stable Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Get Project/Workspace and Scheme
      id: project_info
      run: |
        # Prefer .xcworkspace if it exists (common with CocoaPods/SPM)
        if ls *.xcworkspace &> /dev/null; then
          WORKSPACE_FILE=$(find . -name "*.xcworkspace" -maxdepth 1)
          PROJECT_OR_WORKSPACE_FLAG="-workspace"
          PROJECT_OR_WORKSPACE_NAME=$(basename "$WORKSPACE_FILE")
        else
          PROJECT_FILE=$(find . -name "*.xcodeproj" -maxdepth 1)
          PROJECT_OR_WORKSPACE_FLAG="-project"
          PROJECT_OR_WORKSPACE_NAME=$(basename "$PROJECT_FILE")
        fi

        if [ -z "$PROJECT_OR_WORKSPACE_NAME" ]; then
          echo "Error: No .xcodeproj or .xcworkspace file found."
          exit 1
        fi
        
        echo "PROJECT_OR_WORKSPACE_FLAG=${PROJECT_OR_WORKSPACE_FLAG}" >> $GITHUB_OUTPUT
        echo "PROJECT_OR_WORKSPACE_NAME=${PROJECT_OR_WORKSPACE_NAME}" >> $GITHUB_OUTPUT
        echo "Using ${PROJECT_OR_WORKSPACE_FLAG} ${PROJECT_OR_WORKSPACE_NAME}"

        SCHEME=$(xcodebuild -list $PROJECT_OR_WORKSPACE_FLAG "$PROJECT_OR_WORKSPACE_NAME" | awk '/Schemes:/,/Build Configurations:/' | grep -v -E '(Schemes:|Pods|Tests|Build Configurations:)' | head -n 1 | xargs)
        if [ -z "$SCHEME" ]; then
          echo "Error: Could not automatically determine a buildable scheme."
          exit 1
        fi
        echo "SCHEME_NAME=${SCHEME}" >> $GITHUB_OUTPUT
        echo "Found Scheme: ${SCHEME}"

    - name: Build for Simulator and Verify Architecture
      id: build
      run: |
        # This combination of flags forces an arm64 build for Apple Silicon simulators,
        # overriding any problematic settings in the project file.
        xcodebuild clean build \
          ${{ steps.project_info.outputs.PROJECT_OR_WORKSPACE_FLAG }} "${{ steps.project_info.outputs.PROJECT_OR_WORKSPACE_NAME }}" \
          -scheme "${{ steps.project_info.outputs.SCHEME_NAME }}" \
          -sdk iphonesimulator \
          -derivedDataPath "build/DerivedData" \
          ARCHS=arm64 \
          EXCLUDED_ARCHS="" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

        # --- Diagnostic Step to Confirm Architecture ---
        APP_PATH="build/DerivedData/Build/Products/Debug-iphonesimulator/${{ steps.project_info.outputs.SCHEME_NAME }}.app"
        echo "--- Verifying Built App Architecture ---"
        file "${APP_PATH}/${{ steps.project_info.outputs.SCHEME_NAME }}"
        echo "------------------------------------"
        echo "APP_PATH=${APP_PATH}" >> $GITHUB_OUTPUT

    - name: Compress App for Distribution
      run: |
        APP_PATH="${{ steps.build.outputs.APP_PATH }}"
        ZIP_PATH="${{ steps.project_info.outputs.SCHEME_NAME }}.zip"
        
        echo "Compressing $APP_PATH to $ZIP_PATH..."
        ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "$ZIP_PATH"

    - name: Upload Installable App
      uses: actions/upload-artifact@v4
      with:
        name: simulator-build-app-zip
        path: ${{ steps.project_info.outputs.SCHEME_NAME }}.zip
        retention-days: 5
