# .github/workflows/build-ios.yml

name: Build iOS Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # We are still on an Intel runner, but we'll create builds for both platforms.
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Verify Environment
      run: |
        xcodebuild -version
        echo "Runner architecture: $(uname -m)" # This will show x86_64

    # --- BUILD FOR YOUR M2 MAC ---
    - name: Build for Apple Silicon Simulator (arm64)
      run: |
        echo "🔨 Building for Apple Silicon Simulators (arm64)..."
        xcodebuild clean build \
          -project MusicPlayerApp.xcodeproj \
          -scheme MusicPlayerApp \
          -destination 'platform=iOS Simulator,arch=arm64' \
          -derivedDataPath build/arm64 \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    # --- BUILD FOR INTEL MACS (for completeness) ---
    - name: Build for Intel Simulator (x86_64)
      run: |
        echo "🔨 Building for Intel Simulators (x86_64)..."
        xcodebuild clean build \
          -project MusicPlayerApp.xcodeproj \
          -scheme MusicPlayerApp \
          -destination 'platform=iOS Simulator,arch=x86_64' \
          -derivedDataPath build/x86_64 \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    # --- UPLOAD THE ARTIFACTS ---
    - name: Upload Apple Silicon Simulator Build (For M-series Macs)
      uses: actions/upload-artifact@v4
      with:
        name: simulator-build-arm64
        path: build/arm64/Build/Products/Debug-iphonesimulator/MusicPlayerApp.app
        retention-days: 5

    - name: Upload Intel Simulator Build
      uses: actions/upload-artifact@v4
      with:
        name: simulator-build-x86_64
        path: build/x86_64/Build/Products/Debug-iphonesimulator/MusicPlayerApp.app
        retention-days: 5

    # --- ARCHIVE STEP (remains unchanged) ---
    - name: Create Build Archive (for App Store)
      run: |
        SCHEME_NAME="MusicPlayerApp"
        ARCHIVE_PATH="build/$SCHEME_NAME.xcarchive"
        echo "📦 Archiving scheme '$SCHEME_NAME'..."
        xcodebuild archive \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -archivePath "$ARCHIVE_PATH" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          SKIP_INSTALL=NO
          
    - name: Upload Archive Build
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: archive-build
        path: build/MusicPlayerApp.xcarchive
        retention-days: 5
