# .github/workflows/build-ios.yml

name: Build iOS Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Select Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: List Available Schemes
      run: xcodebuild -list -project MusicPlayerApp.xcodeproj

    - name: Build for iOS Simulator
      run: |
        SCHEME_NAME="MusicPlayerApp"
        # We'll put the output in a predictable location inside the 'build' directory
        DERIVED_DATA_PATH="build/DerivedData"

        echo "🔨 Building scheme '$SCHEME_NAME' for simulator..."
        xcodebuild clean build \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -derivedDataPath "$DERIVED_DATA_PATH" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Create Build Archive
      run: |
        SCHEME_NAME="MusicPlayerApp"
        ARCHIVE_PATH="build/$SCHEME_NAME.xcarchive"

        echo "📦 Archiving scheme '$SCHEME_NAME'..."
        xcodebuild archive \
          -project MusicPlayerApp.xcodeproj \
          -scheme "$SCHEME_NAME" \
          -archivePath "$ARCHIVE_PATH" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          SKIP_INSTALL=NO

    - name: Upload Simulator Build (.app file)
      uses: actions/upload-artifact@v4
      with:
        name: simulator-build-app
        # This path points directly to the compiled .app file
        path: build/DerivedData/Build/Products/Debug-iphonesimulator/MusicPlayerApp.app
        retention-days: 5

    - name: Upload Archive Build (.xcarchive)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: archive-build
        path: build/MusicPlayerApp.xcarchive
        retention-days: 5
