# Simple iOS Simulator Build - GitHub Actions
# File: .github/workflows/ios-simple-build.yml

name: Simple iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
        xcodebuild -version
    
    - name: Install CocoaPods (if needed)
      run: |
        if [ -f "Podfile" ]; then
          gem install cocoapods
          pod install
        fi
    
    - name: List Project Info
      run: |
        echo "=== Directory Contents ==="
        ls -la
        
        echo "=== Finding Projects ==="
        find . -name "*.xcodeproj" -o -name "*.xcworkspace" | head -5
        
        # Set project variables
        if [ -f "*.xcworkspace" ]; then
          echo "WORKSPACE_FILE=$(ls *.xcworkspace | head -1)" >> $GITHUB_ENV
          echo "USE_WORKSPACE=true" >> $GITHUB_ENV
          echo "PROJECT_NAME=$(ls *.xcworkspace | head -1 | sed 's/.xcworkspace//')" >> $GITHUB_ENV
        else
          echo "PROJECT_FILE=$(ls *.xcodeproj | head -1)" >> $GITHUB_ENV
          echo "USE_WORKSPACE=false" >> $GITHUB_ENV
          echo "PROJECT_NAME=$(ls *.xcodeproj | head -1 | sed 's/.xcodeproj//')" >> $GITHUB_ENV
        fi
    
    - name: Show Schemes
      run: |
        if [ "$USE_WORKSPACE" == "true" ]; then
          xcodebuild -workspace "$WORKSPACE_FILE" -list
        else
          xcodebuild -project "$PROJECT_FILE" -list
        fi
    
    - name: Build for Simulator
      run: |
        # Clean first
        rm -rf build/
        
        # Build command
        if [ "$USE_WORKSPACE" == "true" ]; then
          BUILD_ARGS="-workspace $WORKSPACE_FILE"
        else
          BUILD_ARGS="-project $PROJECT_FILE"
        fi
        
        # Build for simulator
        xcodebuild build \
          $BUILD_ARGS \
          -scheme "$PROJECT_NAME" \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -sdk iphonesimulator \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES
    
    - name: Create Archive (Optional)
      run: |
        if [ "$USE_WORKSPACE" == "true" ]; then
          BUILD_ARGS="-workspace $WORKSPACE_FILE"
        else
          BUILD_ARGS="-project $PROJECT_FILE"
        fi
        
        xcodebuild archive \
          $BUILD_ARGS \
          -scheme "$PROJECT_NAME" \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -archivePath "build/$PROJECT_NAME.xcarchive" \
          -sdk iphonesimulator \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: |
          build/
          *.xcarchive
        retention-days: 7
